pair_parameters:
  BTC/USD:
    strategy:
      rsi_oversold: 55
      rsi_overbought: 75
      volume_threshold: 1.3
    ml:
      confidence_threshold: 0.55
    risk:
      trailing_stop_percent: 4.0
      trailing_stop_activation_percent: 6.0
      take_profit_percent: 4.0
      martingale:
        enabled: true
        max_entries: 4
        size_multiplier: 1.4500000000000002
        add_on_drop_percent: 5.0
    _opt:
      score: 2090.8874620856386
      return: 0
      trades: 19
  ETH/USD:
    strategy:
      rsi_oversold: 55
      rsi_overbought: 65
      volume_threshold: 0.9000000000000001
    ml:
      confidence_threshold: 0.65
    risk:
      trailing_stop_percent: 6.5
      trailing_stop_activation_percent: 7.5
      take_profit_percent: 3.0
      martingale:
        enabled: true
        max_entries: 3
        size_multiplier: 1.2000000000000002
        add_on_drop_percent: 4.0
    _opt:
      score: 1664.3548507054616
      return: 0
      trades: 26
  SOL/USD:
    strategy:
      rsi_oversold: 55
      rsi_overbought: 70
      volume_threshold: 1.1
    ml:
      confidence_threshold: 0.65
    risk:
      trailing_stop_percent: 10.0
      trailing_stop_activation_percent: 7.0
      take_profit_percent: 7.0
      martingale:
        enabled: true
        max_entries: 4
        size_multiplier: 1.1500000000000001
        add_on_drop_percent: 4.5
    _opt:
      score: 1156.8826228291216
      return: 0
      trades: 16
  XRP/USD:
    strategy:
      rsi_oversold: 55
      rsi_overbought: 75
      volume_threshold: 0.5
    ml:
      confidence_threshold: 0.9
    risk:
      trailing_stop_percent: 3.0
      trailing_stop_activation_percent: 6.5
      take_profit_percent: 3.0
      martingale:
        enabled: false
        max_entries: 3
        size_multiplier: 1.25
        add_on_drop_percent: 5.0
    _opt:
      score: 1720.8899076347925
      return: 0
      trades: 22
_optimization:
  generated_at: '2026-01-24T18:35:27.230108+00:00'
