_optimization:
  generated_at: '2026-01-28T01:59:40.601904+00:00'
  study_name: scalping_optimization
  period_days: 118
pair_parameters:
  BTC/USD:
    take_profit_percent: 5.0
    stop_loss_percent: 3.0
    rsi_period: 13
    rsi_oversold: 25
    rsi_overbought: 65
    bb_period: 10
    bb_std_dev: 2.0
    vwap_threshold_percent: 0.8
    volume_spike_threshold: 1.75
    min_confirmations: 3
    _metrics:
      score: 1.7024635831593264
      return: 0.028996163359512137
      win_rate: 58.82352941176471
      trades: 17
  ETH/USD:
    take_profit_percent: 6.0
    stop_loss_percent: 3.5
    rsi_period: 13
    rsi_oversold: 40
    rsi_overbought: 60
    bb_period: 15
    bb_std_dev: 2.5
    vwap_threshold_percent: 0.30000000000000004
    volume_spike_threshold: 1.75
    min_confirmations: 4
    _metrics:
      score: -1.0614681426135721
      return: -0.02590666839779806
      win_rate: 41.66666666666667
      trades: 24
  SOL/USD:
    take_profit_percent: 4.0
    stop_loss_percent: 3.5
    rsi_period: 6
    rsi_oversold: 25
    rsi_overbought: 80
    bb_period: 15
    bb_std_dev: 2.0
    vwap_threshold_percent: 0.7000000000000001
    volume_spike_threshold: 1.25
    min_confirmations: 4
    _metrics:
      score: 1.3987162924984329
      return: 0.01289265393451933
      win_rate: 60.0
      trades: 40
  XRP/USD:
    take_profit_percent: 5.0
    stop_loss_percent: 2.0
    rsi_period: 13
    rsi_oversold: 20
    rsi_overbought: 70
    bb_period: 25
    bb_std_dev: 2.25
    vwap_threshold_percent: 0.7000000000000001
    volume_spike_threshold: 2.5
    min_confirmations: 3
    _metrics:
      score: 2.6233397636193834
      return: 0.029989154739264084
      win_rate: 50.0
      trades: 32
