_optimization:
  type: regime_aware
  generated_at: '2026-02-19T20:33:34.010704+00:00'
  period_days: 365
  regimes:
  - bull
  - bear
  - sideways
regime_parameters:
  BTC/USD:
    bear:
      take_profit_percent: 6.0
      stop_loss_percent: 1.0
      rsi_period: 7
      rsi_oversold: 20
      rsi_overbought: 70
      bb_period: 30
      bb_std_dev: 1.75
      vwap_threshold_percent: 0.5
      volume_spike_threshold: 1.5
      min_confirmations: 2
      _metrics:
        score: .inf
        return: 0.009394762110791089
        win_rate: 100.0
        trades: 1
  ETH/USD: {}
  SOL/USD:
    bear:
      take_profit_percent: 8.0
      stop_loss_percent: 1.0
      rsi_period: 7
      rsi_oversold: 20
      rsi_overbought: 80
      bb_period: 30
      bb_std_dev: 2.25
      vwap_threshold_percent: 0.7000000000000001
      volume_spike_threshold: 2.25
      min_confirmations: 1
      _metrics:
        score: -5.170358466627737
        return: 0.010264962785190073
        win_rate: 50.0
        trades: 2
  XRP/USD:
    bear:
      take_profit_percent: 3.5
      stop_loss_percent: 2.0
      rsi_period: 8
      rsi_oversold: 40
      rsi_overbought: 65
      bb_period: 15
      bb_std_dev: 2.25
      vwap_threshold_percent: 0.9
      volume_spike_threshold: 1.0
      min_confirmations: 2
      _metrics:
        score: .inf
        return: 0.010332096990373974
        win_rate: 100.0
        trades: 1
