_optimization:
  generated_at: '2026-02-28T12:38:02.818389+00:00'
  study_name: scalping_optimization
  period_days: 90
pair_parameters:
  BTC/USD:
    take_profit_percent: 2.0
    stop_loss_percent: 1.0
    rsi_period: 8
    rsi_oversold: 20
    rsi_overbought: 60
    bb_period: 25
    bb_std_dev: 2.0
    vwap_threshold_percent: 0.30000000000000004
    volume_spike_threshold: 1.5
    min_confirmations: 2
    _metrics:
      score: 1.5714742761193858
      return: 0.006805331698455484
      win_rate: 60.0
      trades: 15
  ETH/USD:
    take_profit_percent: 8.0
    stop_loss_percent: 1.0
    rsi_period: 13
    rsi_oversold: 40
    rsi_overbought: 75
    bb_period: 25
    bb_std_dev: 1.5
    vwap_threshold_percent: 0.2
    volume_spike_threshold: 2.25
    min_confirmations: 3
    _metrics:
      score: 11.981593793913959
      return: 0.024539844847848873
      win_rate: 100.0
      trades: 2
  SOL/USD:
    take_profit_percent: 3.0
    stop_loss_percent: 1.0
    rsi_period: 6
    rsi_oversold: 40
    rsi_overbought: 60
    bb_period: 15
    bb_std_dev: 2.25
    vwap_threshold_percent: 0.1
    volume_spike_threshold: 1.25
    min_confirmations: 2
    _metrics:
      score: -0.7345481023670763
      return: -0.018248137028140446
      win_rate: 45.45454545454545
      trades: 22
  XRP/USD:
    take_profit_percent: 5.0
    stop_loss_percent: 2.0
    rsi_period: 5
    rsi_oversold: 30
    rsi_overbought: 65
    bb_period: 20
    bb_std_dev: 1.75
    vwap_threshold_percent: 0.30000000000000004
    volume_spike_threshold: 2.25
    min_confirmations: 2
    _metrics:
      score: 1.8196686139436906
      return: 0.010136588519036194
      win_rate: 50.0
      trades: 10
  DOGE/USD:
    take_profit_percent: 6.5
    stop_loss_percent: 1.5
    rsi_period: 5
    rsi_oversold: 25
    rsi_overbought: 65
    bb_period: 30
    bb_std_dev: 1.75
    vwap_threshold_percent: 0.9
    volume_spike_threshold: 2.25
    min_confirmations: 1
    _metrics:
      score: 0.013714245634314892
      return: -0.00933381098888276
      win_rate: 25.0
      trades: 28
  ADA/USD:
    take_profit_percent: 8.0
    stop_loss_percent: 1.5
    rsi_period: 6
    rsi_oversold: 30
    rsi_overbought: 65
    bb_period: 30
    bb_std_dev: 2.5
    vwap_threshold_percent: 0.5
    volume_spike_threshold: 2.5
    min_confirmations: 1
    _metrics:
      score: -0.11231384380513654
      return: -0.009374281094075013
      win_rate: 26.08695652173913
      trades: 23
  LINK/USD:
    take_profit_percent: 2.0
    stop_loss_percent: 1.5
    rsi_period: 8
    rsi_oversold: 30
    rsi_overbought: 60
    bb_period: 30
    bb_std_dev: 1.75
    vwap_threshold_percent: 0.8
    volume_spike_threshold: 1.25
    min_confirmations: 2
    _metrics:
      score: 4.3165989244395515
      return: 0.024507664280459904
      win_rate: 80.0
      trades: 10
  AVAX/USD:
    take_profit_percent: 5.5
    stop_loss_percent: 2.5
    rsi_period: 8
    rsi_oversold: 20
    rsi_overbought: 75
    bb_period: 30
    bb_std_dev: 1.5
    vwap_threshold_percent: 0.2
    volume_spike_threshold: 1.5
    min_confirmations: 2
    _metrics:
      score: 3.8746576927007084
      return: 0.033347661670916934
      win_rate: 60.0
      trades: 10
